# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username : joe
  password : joe
  database: my_database

test: &test
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username : joe
  password : joe
  database: my_database

production:
  adapter: postgresql
  database: my_database
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
